### ISSUE TITLE
Show positive feedback also for orange, red and empty tiles

### ISSUE THREAD

**Issue by cgiovando** [mapswipe/app-feedback#7]
The "reward" / "thank you" messages that appear after tapping a few green tiles are great.

Some tasks though have no tile to get tagged green, but still there's effort by the mapper to check that every one of them is either empty (no buildings or roads), a maybe (orange) or the imagery is not readable (cloudy or missing).

This effort should be rewarded in the same or similar way of when the user taps green. Knowing that no buildings are in one area I think it's as valuable as knowing where they are.

**Comment by althio** [comment]
I agree, it should not depend on the tagged state and only for yes/green. It should be for a number of reviewed tiles, and all states should be taken into account somehow.

It is even more disconcerting (for the lack of a better word right now) that when you tap twice or more, you sometimes get a glimpse of the 'nice message' and it disappears as you select the correct tile state.

So maybe a timer would be useful.

**Comment by laurentS** [comment]
Moved to main mapswipe repo
