### ISSUE TITLE
Crashes on startup after first launch - but works from notification

### ISSUE THREAD

**Issue by bgirardot** [mapswipe/app-feedback#9]
As has been reported by others, after installing mapswipe on android 6.0.1 it will launch once and you can use it fine, but any additional attempts to launch the app it crashes during start up.

However, the important new detail for me is that if the app is launched by single or double tapping on an android notification and not just launching it from the home screen, it will launch successfully.

Other attempts to launch it from the home screen still crash, but then going back up to notifications and launching it that way works again.

**Comment by PimDeWitte** [comment]
That's a very strange error. I'll look into it and update this post.

**Comment by bgirardot** [comment]
This seems to be fixed in the last update. Thank you very much.
